# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: nightly update

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-15

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Update
        run: ./update_all.py
        env:
          GH_TOKEN: ${{ github.token }}
