# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: nightly update

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-15

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python dependencies
        run: pip3 install packaging

      - name: Update
        run: |
          brew tap kdab/tap_testing ${PWD}
          ./update_all.py
        env:
          GH_TOKEN: ${{ github.token }}
